### ISSUE TITLE
Throw "Email gönderilmesi zorunludur" error when card user key not sent

### ISSUE THREAD

**Issue by lahmacun** [iyzico/iyzipay-php#95] opened 2019-09-13 20:15 UTC
I'm not sure if this is an error or not but in my project I was trying to add second card to the user but I got this error. Then I realized I forgot to send CardUserKey parameter (I was sending null or empty value). But API responded with "Email gönderilmesi zorunludur.". I don't know why API throwing this error but If you can respond it with error like "Email veya Card User Key gönderilmesi zorunludur." or "Card User Key gönderilmesi zorunludur." It'll be more clear error message.

Btw, great Library and really clear code. Big congratulations to Iyzico team.

**Comment by byasarcse** [comment] 2023-08-10 13:13
Hello @lahmacun,

If you can share the endpoint and service response with destek@iyzico.com we would like to investigate. For now we couldn't reproduce the issue. 

Closing the issue due to timed out.

**Closed by byasarcse** 2023-08-10 13:13 UTC
